Port to pipeline elements
OpenTabletDriver/TabletDriverFilters pull request #17
Opened 2021-04-13 12:50 UTC by X9VoiD

Marked draft until `output-pipeline` gets merged to OTD master

2021-04-13 13:07 UTC, InfinityGhost requested changes

2021-04-13 13:07 UTC, InfinityGhost commented on HawkuFilters/Smoothing.cs
> +
Too many blank lines

2021-04-13 13:28 UTC, X9VoiD commented on HawkuFilters/Smoothing.cs
> +
Fixed

2022-01-03 07:15 UTC, gonX commented
Fixes #21 probably

2022-01-10 15:51 UTC, InfinityGhost approved these changes

2022-01-10 15:51 UTC, merged